// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    return $('#tag-edit-cloud .remove').on('ajax:success', function(e, data, status, xhr) {
      return $(this).parents('li').remove();
    }).bind("ajax:error", function(e, data, status, xhr) {
      return alert("Could not find this tag.");
    });
  });

}).call(this);
